apiVersion: v1
kind: Service
metadata:
  name: coffeehouse-service
spec:
  type: NodePort
  selector:
    app: coffeehouse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
